name: Filili
favicon: null
layout_spectrum: 0.3690172340720892
typography_spectrum: 0.2470490583218634
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.22903265873901546
  lightness: 0.2835217877291143
  saturation: 0.7176770218648016
  rhythmicContrast: 0.6072641084901989
purpose: []
